Repository robinzyb/ECToolkits, pull requests merged in 2024-12, with the labels that each got.

#37 Modify the doc for atom density analysis
  .github/workflows/pub-pypi.yml
  README.md
  docs/analysis/atom_density.md
  docs/analysis/figures/rutile_interface.png
  ectoolkits/utils/rutile110.py
Labels: documentation

#38 add merged frc comp in dptest plot
  docs/plots/dpmd.md
  ectoolkits/plots/dpmd.py
  tests/plots/dpmd/test_plot_dpmd.py
Labels: Enhancement

#36 Water dipole analysis
  ectoolkits/analysis/water.py
  ectoolkits/utils/utils.py
  tests/analysis/water/P-water.dat
  tests/analysis/water/SnO2-water.dat
  tests/analysis/water/gen_answer.py
  tests/analysis/water/test_water.py
Labels: New-Feature
